Add potential security issues in decoding
ietf-wg-cellar/flac-specification pull request #138
Opened 2022-02-23 19:13 UTC by ktmf01

Add text as proposed in #109, document that all metadata in the frame header can change and that this poses a security risk on decoding. Also document that relying on coded numbers can pose a security risk. Fixes #109

2022-03-08 09:16 UTC, retokromer approved these changes

2022-03-10 10:27 UTC, ktmf01 commented
@JeromeMartinez Could you please review these changes? In the discussion of issue #109 you had some thoughts on (not) adding restrictions to the coded number. In this PR I've added such restrictions because not having them makes seeking in a FLAC file impossible if it is not embedded in ogg or matroska.

2022-04-12 11:42 UTC, retokromer commented
ping @JeromeMartinez

2022-08-18 15:31 UTC, retokromer commented
ping @JeromeMartinez

2022-08-18 18:50 UTC, JeromeMartinez requested changes

2022-08-18 18:50 UTC, JeromeMartinez commented on flac.md
> +Each frame header stores the audio sample rate, number of bits per sample and number of channels independently of other frame headers. This was done to simplify streaming of FLAC files over the inter
```suggestion
Each frame header stores the audio sample rate, number of bits per sample and number of channels independently of the Streaminfo metadata block and other frame headers. This was done to permit streaming of FLAC files over the internet (for example in internet radio) but it also allows these properties to change mid-stream. Because not all environments in which FLAC decoders are used are able to cope with changes to these parameters during playback, a decoder MAY choose to stop decoding on such a change. A decoder that does not check for such a change could be vulnerable to buffer overflows. See also [the section on security considerations](#security-considerations).
```

2022-08-18 19:48 UTC, ktmf01 commented on flac.md
> +Each frame header stores the audio sample rate, number of bits per sample and number of channels independently of other frame headers. This was done to simplify streaming of FLAC files over the inter
Thanks for the suggestion. I think streaming is still possible without this. As far as I know, most streaming today is done with unicast, where each client gets its own stream, including the header. FLAC streaming is commonly implemented as such, and with that, each decoder receives a streaminfo block and does not need the frame headers to convey information. One could call it: "encode once, mux as required"

It is needed with multicast streaming though, of which I haven't seen any example for FLAC. That's why I chose the word 'simplify'. Perhaps `This was done to permit multicasting of FLAC files over the internet` is a good middle ground here?

I presume you find this addition otherwise OK? It doesn't preclude FLAC files with changing parameters, but it makes it clear it is not a feature that should be relied upon?

2022-08-19 10:29 UTC, JeromeMartinez commented on flac.md
> +Each frame header stores the audio sample rate, number of bits per sample and number of channels independently of other frame headers. This was done to simplify streaming of FLAC files over the inter
> `This was done to permit multicasting of FLAC files over the internet`

`This was done to permit multicasting of FLAC` would be enough actually, Internet is only a mean, it could be broadcasted by satellite too :).

2022-08-19 11:18 UTC, ktmf01 commented on flac.md
> +Each frame header stores the audio sample rate, number of bits per sample and number of channels independently of other frame headers. This was done to simplify streaming of FLAC files over the inter
I've incorporated the suggested change

2022-08-19 11:22 UTC, JeromeMartinez approved these changes

2022-08-19 19:46 UTC, merged